FROM python:3.10.4

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

COPY Pipfile Pipfile.lock ./
RUN python3 -m pip install --upgrade pip
RUN pip install pipenv
RUN pipenv install --dev --system

WORKDIR /auth
COPY / .


CMD uvicorn main:app --reload --host 0.0.0.0 --port 5001
